base:
  port: 8002
  base_url: "dwz.cn/"
  health_check_url: "/health"
  health_check_port: 8003

log:
  # 日志路径
  log_path: "./short_url.log"
  # 日志分割时间
  rotation_time: 86400

snowflake:
  start_timestamp: 1602228331822
  datacenter_id: 1
  worker_id: 1
  sequence_bits: 12
  datacenterid_bits: 5
  workerid_bits: 5

mysql:
  ip: 9.134.242.17
  port: 3306
  user: root
  password: 123456
  connect_timeout: 10
  database_name: short_url
  # 读写超时时间为0代表不限制
  read_timeout: 0
  write_timeout: 0