// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: short_url.proto

package ShortUrl

import (
	context "context"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Code int32

const (
	Code_OK            Code = 0
	Code_ERR_PARAMETER Code = 10
	Code_ERR_SERVICE   Code = 20
	Code_ERR_NOT_FOUND Code = 30
	Code_ERR_UNKNOWN   Code = 100
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:   "OK",
		10:  "ERR_PARAMETER",
		20:  "ERR_SERVICE",
		30:  "ERR_NOT_FOUND",
		100: "ERR_UNKNOWN",
	}
	Code_value = map[string]int32{
		"OK":            0,
		"ERR_PARAMETER": 10,
		"ERR_SERVICE":   20,
		"ERR_NOT_FOUND": 30,
		"ERR_UNKNOWN":   100,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_short_url_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_short_url_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{0}
}

type SetUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SetUrlReq) Reset() {
	*x = SetUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUrlReq) ProtoMessage() {}

func (x *SetUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUrlReq.ProtoReflect.Descriptor instead.
func (*SetUrlReq) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{0}
}

func (x *SetUrlReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetUrlRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     Code   `protobuf:"varint,1,opt,name=code,proto3,enum=ShortUrl.Code" json:"code,omitempty"`
	ShortUrl string `protobuf:"bytes,2,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *SetUrlRsp) Reset() {
	*x = SetUrlRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetUrlRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUrlRsp) ProtoMessage() {}

func (x *SetUrlRsp) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUrlRsp.ProtoReflect.Descriptor instead.
func (*SetUrlRsp) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{1}
}

func (x *SetUrlRsp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *SetUrlRsp) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetAfterForwardUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetAfterForwardUrlReq) Reset() {
	*x = GetAfterForwardUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAfterForwardUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAfterForwardUrlReq) ProtoMessage() {}

func (x *GetAfterForwardUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAfterForwardUrlReq.ProtoReflect.Descriptor instead.
func (*GetAfterForwardUrlReq) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{2}
}

func (x *GetAfterForwardUrlReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetAfterForwardUrlRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code   `protobuf:"varint,1,opt,name=code,proto3,enum=ShortUrl.Code" json:"code,omitempty"`
	LongUrl string `protobuf:"bytes,2,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *GetAfterForwardUrlRsp) Reset() {
	*x = GetAfterForwardUrlRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAfterForwardUrlRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAfterForwardUrlRsp) ProtoMessage() {}

func (x *GetAfterForwardUrlRsp) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAfterForwardUrlRsp.ProtoReflect.Descriptor instead.
func (*GetAfterForwardUrlRsp) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{3}
}

func (x *GetAfterForwardUrlRsp) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *GetAfterForwardUrlRsp) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_short_url_proto protoreflect.FileDescriptor

var file_short_url_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x1d, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0b,
	0xfa, 0x42, 0x08, 0x72, 0x06, 0x18, 0xf6, 0x3f, 0x88, 0x01, 0x01, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x22, 0x4b, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x18, 0x14, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x55, 0x72, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x2a, 0x56, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x52, 0x52, 0x5f,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x45,
	0x52, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x14, 0x12, 0x11, 0x0a, 0x0d,
	0x45, 0x52, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x1e, 0x12,
	0x0f, 0x0a, 0x0b, 0x45, 0x52, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x64,
	0x32, 0xa6, 0x01, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x12, 0x13, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x2e, 0x53,
	0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x58, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x66, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x55, 0x72, 0x6c, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_short_url_proto_rawDescOnce sync.Once
	file_short_url_proto_rawDescData = file_short_url_proto_rawDesc
)

func file_short_url_proto_rawDescGZIP() []byte {
	file_short_url_proto_rawDescOnce.Do(func() {
		file_short_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_short_url_proto_rawDescData)
	})
	return file_short_url_proto_rawDescData
}

var file_short_url_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_short_url_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_short_url_proto_goTypes = []interface{}{
	(Code)(0),                     // 0: ShortUrl.Code
	(*SetUrlReq)(nil),             // 1: ShortUrl.SetUrlReq
	(*SetUrlRsp)(nil),             // 2: ShortUrl.SetUrlRsp
	(*GetAfterForwardUrlReq)(nil), // 3: ShortUrl.GetAfterForwardUrlReq
	(*GetAfterForwardUrlRsp)(nil), // 4: ShortUrl.GetAfterForwardUrlRsp
}
var file_short_url_proto_depIdxs = []int32{
	0, // 0: ShortUrl.SetUrlRsp.code:type_name -> ShortUrl.Code
	0, // 1: ShortUrl.GetAfterForwardUrlRsp.code:type_name -> ShortUrl.Code
	1, // 2: ShortUrl.ShortUrlService.SetShortUrl:input_type -> ShortUrl.SetUrlReq
	3, // 3: ShortUrl.ShortUrlService.GetAfterForwardUrl:input_type -> ShortUrl.GetAfterForwardUrlReq
	2, // 4: ShortUrl.ShortUrlService.SetShortUrl:output_type -> ShortUrl.SetUrlRsp
	4, // 5: ShortUrl.ShortUrlService.GetAfterForwardUrl:output_type -> ShortUrl.GetAfterForwardUrlRsp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_short_url_proto_init() }
func file_short_url_proto_init() {
	if File_short_url_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_short_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_short_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetUrlRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_short_url_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAfterForwardUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_short_url_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAfterForwardUrlRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_short_url_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_short_url_proto_goTypes,
		DependencyIndexes: file_short_url_proto_depIdxs,
		EnumInfos:         file_short_url_proto_enumTypes,
		MessageInfos:      file_short_url_proto_msgTypes,
	}.Build()
	File_short_url_proto = out.File
	file_short_url_proto_rawDesc = nil
	file_short_url_proto_goTypes = nil
	file_short_url_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShortUrlServiceClient is the client API for ShortUrlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortUrlServiceClient interface {
	SetShortUrl(ctx context.Context, in *SetUrlReq, opts ...grpc.CallOption) (*SetUrlRsp, error)
	GetAfterForwardUrl(ctx context.Context, in *GetAfterForwardUrlReq, opts ...grpc.CallOption) (*GetAfterForwardUrlRsp, error)
}

type shortUrlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShortUrlServiceClient(cc grpc.ClientConnInterface) ShortUrlServiceClient {
	return &shortUrlServiceClient{cc}
}

func (c *shortUrlServiceClient) SetShortUrl(ctx context.Context, in *SetUrlReq, opts ...grpc.CallOption) (*SetUrlRsp, error) {
	out := new(SetUrlRsp)
	err := c.cc.Invoke(ctx, "/ShortUrl.ShortUrlService/SetShortUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortUrlServiceClient) GetAfterForwardUrl(ctx context.Context, in *GetAfterForwardUrlReq, opts ...grpc.CallOption) (*GetAfterForwardUrlRsp, error) {
	out := new(GetAfterForwardUrlRsp)
	err := c.cc.Invoke(ctx, "/ShortUrl.ShortUrlService/GetAfterForwardUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortUrlServiceServer is the server API for ShortUrlService service.
type ShortUrlServiceServer interface {
	SetShortUrl(context.Context, *SetUrlReq) (*SetUrlRsp, error)
	GetAfterForwardUrl(context.Context, *GetAfterForwardUrlReq) (*GetAfterForwardUrlRsp, error)
}

// UnimplementedShortUrlServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShortUrlServiceServer struct {
}

func (*UnimplementedShortUrlServiceServer) SetShortUrl(context.Context, *SetUrlReq) (*SetUrlRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetShortUrl not implemented")
}
func (*UnimplementedShortUrlServiceServer) GetAfterForwardUrl(context.Context, *GetAfterForwardUrlReq) (*GetAfterForwardUrlRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAfterForwardUrl not implemented")
}

func RegisterShortUrlServiceServer(s *grpc.Server, srv ShortUrlServiceServer) {
	s.RegisterService(&_ShortUrlService_serviceDesc, srv)
}

func _ShortUrlService_SetShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortUrlServiceServer).SetShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortUrl.ShortUrlService/SetShortUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortUrlServiceServer).SetShortUrl(ctx, req.(*SetUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortUrlService_GetAfterForwardUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAfterForwardUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortUrlServiceServer).GetAfterForwardUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShortUrl.ShortUrlService/GetAfterForwardUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortUrlServiceServer).GetAfterForwardUrl(ctx, req.(*GetAfterForwardUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShortUrlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShortUrl.ShortUrlService",
	HandlerType: (*ShortUrlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetShortUrl",
			Handler:    _ShortUrlService_SetShortUrl_Handler,
		},
		{
			MethodName: "GetAfterForwardUrl",
			Handler:    _ShortUrlService_GetAfterForwardUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "short_url.proto",
}
